# Generated by Django 3.1.2 on 2020-11-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car',
            new_name='cart',
        ),
    ]
